# Generated by Django 4.2.7 on 2023-11-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_email_address',
            field=models.CharField(default='test@test.nl', max_length=320),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=320),
        ),
    ]
