# Generated by Django 4.2.7 on 2023-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_family_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_email_address',
            field=models.CharField(max_length=320, unique=True),
        ),
    ]
