# Generated by Django 4.2.7 on 2023-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_family_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
